### ISSUE TITLE
dvcapture: GUI controls confuse multiple decks of same model

### ISSUE THREAD

**Issue by belak1** [mipops/dvrescue#634] opened 2022-11-15 17:44 UTC
I'm conducting simultaneous capture using the Capture tab of the GUI but sometimes the controls either aren't clear or change which deck is being controlled. At the top of each preview, the GUI prints the deck name, but for two decks of the same model, this is identical.

Computer: Mac Pro (Late 2013) running macOS Monterey 12.6.1
DVRescue: Version 0.22.10
Deck: Sony HVR-M35U (x2) connected with Thunderbolt 2

![Screen Shot 2022-11-15 at 9 37 24 AM](https://user-images.githubusercontent.com/60083346/201988782-d0acba5c-759d-47d1-91b3-e55bab71f598.png)

I'd like to be able to start capture on one deck, then queue a tape in the other deck and start that one. With both decks connected and appearing in DVRescue, I click on the deck name of the first one, press record underneath it, and start the capture. Then I click on the name of the second deck and try to use the deck controls. Clicking "stop" or "rewind" will control the first deck instead, halting the capture in progress. At one point yesterday, clicking "record" on the second deck started a second capture stream of the same tape already playing in the first deck.

I'm also not 100% sure which M35U I'm looking at in each window until the tape starts. What I found works best is making sure I have both tapes queued at the start in the decks before starting the capture process. I start recording with one window, discover which deck it starts, then start recording in the other to activate the second deck.

**Comment by libbyhopfauf** [comment] 2022-11-30 01:37
We have some identical decks at MIPoPS. I'll do some testing and see if I experience the same thing.

**Comment by libbyhopfauf** [comment] 2022-12-02 23:13
@dericed @belak1 I can confirm that I experience the same inconsistencies for two decks with identical names.

**Comment by dericed** [comment] 2023-03-24 14:55
Hi @belak1, @libbyhopfauf can you review with the latest daily build at https://old.mediaarea.net/download/snapshots/binary/dvrescue-gui. The guid for each deck should now be listed to the left of the deck's name.

**Comment by libbyhopfauf** [comment] 2023-03-25 03:07
@dericed I can test next week when I have access to two of the same decks in the same room.

**Comment by dericed** [comment] 2023-12-08 19:55
@elderorb, can you add the device id to the title bar of the capture window. So, example: "HDV-VCR (Sony HVR-M35U)  - 0x12345678"

**Comment by libbyhopfauf** [comment] 2024-11-26 02:42
Closing since this is now incorporated into the GUI and CLI :)

**Closed by libbyhopfauf** 2024-11-26 02:42 UTC
