### ISSUE TITLE
Capture from CLI creates 0KB .dv file

### ISSUE THREAD

**Issue by ghost** [mipops/dvrescue#675] opened 2023-02-21 01:38 UTC
I am using the CLI to perform capture, with this command: 

`dvrescue device://0 --cmd play --capture -m my_capture.dv `

This runs without error, but the resulting .dv file is 0KB.

Is this an actual issue, or am I just missing something in the command syntax here?

I am running MacOS Monterey 12.6.3, on an Intel Mac.
I am running DVRescue v.0.21.11.20230218 (from the daily builds).

I'm using the CLI because I've been unable to get my deck to show in the GUI (similar to issues #668 and #674).

Any help/guidance is appreciated. Thank you.

**Comment by JeromeMartinez** [comment] 2023-02-21 07:37
Not sure it helps, but for being sure that the issue is not due to many commands: please try `dvrescue device://0 -m my_capture.dv`

**Comment by dericed** [comment] 2023-02-21 15:24
Hi @ace8temp, the `-m` flag is in the help doc (from `-h`), but it's a short-form of `--merge`. Can you check in Systems Preferences under Security and make sure that dvrescue is okayed to access your camera (macOS considers the dv deck as a camera).

**Comment by ace8temp** [comment] 2023-02-21 16:52
@JeromeMartinez - running `dvrescue device://0 -m my_capture.dv` still creates a 0KB .dv file. 

However, the terminal output is different. Whereas before it didn't give me any output when I ended the capture, the adjusted syntax above returns:

_Frames discarded in output: 525 = 100.0000% of frames discarded for non-standard playback speed._

Playback speed is definitely normal (1.0), so it's odd that it's saying "100% of frames discarded for non-standard playback speed." This is why I originally added the `--cmd play` option, to see if it needed to be "told" playback speed was 1.0, but that didn't seem to help.

@dericed - thank you for the clarification regarding the -m switch. 

I was prompted to grant camera access to the terminal during my first capture via the CLI. However, the DVRescue App has not prompted me to do this yet, and unfortunately the camera in macOS settings doesn't provide the +/- option to manually add an application. However, I have allowed DV Rescue and terminal full disk access, which does still provide the +/- option to manually add in settings.

Also, `dvrescue --list_devices` and a new movie capture in Quicktime both identify my deck.

**Comment by JeromeMartinez** [comment] 2023-02-21 16:56
> the adjusted syntax above returns:

So we have frames, a good point.
Please try again, with `dvrescue device://0 -m my_capture.dv --verbosity 9 --merge-output-speed`
(` --merge-output-speed` for storing the frames even if non-standard playback speed is detected, ` --verbosity 9` for more info about the frames, including the detected speed)

> However, the DVRescue App has not prompted me to do this yet

Argh! We'll try to find a way to force it... No ETA.

**Comment by ace8temp** [comment] 2023-02-21 17:57
> Please try again, with `dvrescue device://0 -m my_capture.dv --verbosity 9 --merge-output-speed`

Nice! This worked. The .dv file is no longer 0KB, and it has now captured the video stream.

Result shows: _0 =   0.0000% of blocks have errors, in      0 =   0.0000% of frames_

Sample of the frame output:

     #|Abst  |HH:MM:SS:FF|U|S|Comments
     0 870933 00:01:11;22 0
     1 870943 00:01:11;23 0
     2 870953 00:01:11;24 0
     3 870963 00:01:11;25 0

Does this indicate the detected speed?

Also - quick side question - what is the best way to gracefully stop capture from the CLI? Just pressing stop on the deck itself, or something else?

**Comment by JeromeMartinez** [comment] 2023-02-21 18:02
> Does this indicate the detected speed?

there is no remark listed so normal speed, weird that you then get "non-standard playback speed" info and discard of the frames.
Could you provide a couple of frames (link at my email address if it is not possible to share publicly) so I try to reproduce the issue?

> Also - quick side question - what is the best way to gracefully stop capture from the CLI?

Now Ctrl-C should work, but it will not stop the deck (maybe it should...).
For stopping the deck so the capture, in another terminal `dvrescue device://0 --cmd stop`

**Comment by dericed** [comment] 2023-02-21 18:38
Hi @ace8temp, by default we stopped outputting frames if the playback speed (as noted within the frames) was not the standard playback speed (which I think is 31 and 32). The idea here was that if the deck is playing and then gets to the end of the tape and starts auto-rewinding, then we don't really need (or want?) to capture the jumbling frames that come over when the deck is rewinding. From my own test I was always finding standard playback speed as 31/32 but yours are some how different. Would you mind sharing a small sample?

**Comment by ace8temp** [comment] 2023-02-21 19:21
Thank you @JeromeMartinez and @dericed. 

Could you please describe the workflow for how best to share a sample of frames so that you can get what you need?
Do you just want the .dv file from a small capture using the working syntax above, or something else?

To keep it private, I'll share this via email, so please also provide the best email to submit the attachment to.

**Comment by dericed** [comment] 2023-02-21 19:23
You could run `head -c 480000 YOURCAPTURE.dv > HEREYOUGO.dv` and then zip the result and attach it to a response here. (480000 is 4 times the size of an NTSC frame, so it would give us 4 frames which is probably enough)

**Comment by JeromeMartinez** [comment] 2023-02-21 19:38
> please also provide the best email to submit the attachment to.

jerome@mediaarea.net

**Comment by ace8temp** [comment] 2023-02-22 02:04
I've emailed the requested file. The email subject line is the same as the issue's subject line here. Please let me know if I should adjust my capture in any way based on your findings.

While you investigate, I do have one follow-up question: using the GUI, the capture documentation says:

_When dvcapture encounters an error, it will automatically rewind and try to capture the frames containing errors (more than once if needed; if unable to capture full frames, after 3 attempts, it will move on) to the next portion of the tape._

This is a great feature. Is there a way to initiate the automatic 3 attempts using capture from the CLI? If so, could you provide the syntax? 

Thank you for all of your help here.

**Comment by JeromeMartinez** [comment] 2023-02-22 11:18
> I've emailed the requested file.

Got it, we'll check.

>  Is there a way to initiate the automatic 3 attempts using capture from the CLI? If so, could you provide the syntax?

` --rewind-count 3`

**Comment by ace8temp** [comment] 2023-02-22 15:10
> Got it, we'll check.

Perfect. Let me know if you need anything further.

> --rewind-count 3

Thank you. I had tried this, but it didn't seem to initiate a rewind /recapture after it encountered errors. Does it initiate a rewind/recapture after a certain amount of time or after the tape ends?

If you have the time, I do have another - somewhat related - question: Given my tape deck behavior right now (issues identifying playback speed), would this still be the correct syntax to use for merging multiple .dv capturers together to produce the best one?

`dvrescue my_capture_1.dv my_capture_2.dv -m my_capture_merged.dv --merge-output-speed `

Again, thank you for all of the help here. I hope you don't mind me asking these side-questions while investing the original issue. This tool has been extremely helpful, and having this additional clarity on some of the behavior has been invaluable. So thank you.

**Comment by kristofferR** [comment] 2023-02-22 15:40
Thanks for tagging me on this (with #674 ). 

I've already got the footage on my mac using vrecord, but I'd like to try to get dvrescue working, with rewind-count, too.

BTW, your documentation is horrible. Half the time the documentation refer to a bunch of hour long presentations and a blog that doesn't contain the cli commands, and the other half a page with tiny windows that is a horrible experience to read and a bunch of dead links. It should be done like this: https://leolabs.org/blog/capture-minidv-on-macos

**Comment by privatezero** [comment] 2023-02-23 17:01
> I could try to fix it, but the "Change this page on Github" link 404s.

@kristofferR thanks for reporting that 404 - the correct direct link to the raw documentation in the repo is: https://github.com/mipops/dvrescue/tree/main/docs. The docs are based in Jekyll, so any suggested edits can be made by modifying the markdown.

**Comment by ace8temp** [comment] 2023-04-02 02:56
@JeromeMartinez , @dericed 

Were you able to deduce anything from the clip I shared?

I currently have a tape with both 12-bit and 16-bit audio. I’m trying to keep the tape capture contained to one .dv file. But, when I capture it as one, the `--merge-output-speed` option causes problems  due to the two different audio bitrates contained in one file. Specifically, the clip with the 16-bit audio plays back super slow.

To avoid this, I would like to run the capture without the `--merge-output-speed` option, but I run in to the original issue described  where all frames are discarded due to “non-standard playback speed.”

**Comment by JeromeMartinez** [comment] 2023-04-04 06:45
> Were you able to deduce anything from the clip I shared?

Apologizes for the delay, I check that this week.

**Comment by libbyhopfauf** [comment] 2024-12-17 23:49
It looks like the original user who posted this deleted their account. This also appears to be a duplicate of issue #674. Closing for now, but please reopen if needed.

**Closed by libbyhopfauf** 2024-12-17 23:49 UTC
