### ISSUE TITLE
Audio and video become out of sync in some files after running dvpackager

### ISSUE THREAD

**Issue by iamdamosuzuki** [mipops/dvrescue#127] opened 2020-07-28 17:41 UTC
I've found that some files have bad audio sync after being run through dvpackager. The sync fall out at specific locations, which line up with moments in the files with broken/missing timecode or repeating video frames.

**Comment by dericed** [comment] 2020-07-28 19:09
Hi @iamdamosuzuki, some dv transfers result in frames where there is no audio source pack, so although there is audio data there (as that place is always reserved in DV), there is no metadata to define it. Over at https://github.com/mipops/dvrescue/issues/123 I referred to these as faux frames as they don't contain anything particularly helpful, such no audio data but concealed video data. When ffmpeg reads these frames they output video but do not output audio, so it creates a loss of sync in the outputs of FFmpeg's DV demuxer.

Michael Niedermayer drafted a patch where an option can be supplied to tell FFmpeg to recycle the audio source pack from prior frames to frames without an audio source pack. To test this do:

```
git clone git://source.ffmpeg.org/ffmpeg ffmpeg-dv
cd ffmpeg-dv
curl https://gist.githubusercontent.com/dericed/3db9f59666636b6f9a0a57015f6cd8b2/raw/179e8563232867ec7e9c73bb3cdc93ced2b5ca31/dv.patch -O
git apply dv.patch
./configure && make
brew unlink ffmpeg
sudo make install
```

Then within dvpackager replace `ffmpeg ` with `ffmpeg -dvaudio_concealment pass `.

**Comment by iamdamosuzuki** [comment] 2020-07-29 03:17
This works! very cool. The audio stays in sync the file trucks through the weird timecode section without failing.

**Comment by dericed** [comment] 2020-07-29 15:36
Going to keep this open, until the fix is in ffmpeg & dvpacakager.

**Comment by iamdamosuzuki** [comment] 2020-07-29 19:44
ah good point. Thanks!

**Comment by dericed** [comment] 2020-11-11 20:13
Hey @iamdamosuzuki, can you do brew upgrade to update ffmpegdecklink. With that and git master here, dvpackager should use a patch in ffmpegdecklink and the aresample filter to keep audio and video in sync.

**Comment by dericed** [comment] 2020-11-19 19:23
psst @iamdamosuzuki, comments?

**Comment by cmhosale** [comment] 2021-01-12 20:14
glad to jump in as a tester on some of this, as I have lots of problematic DV preservation files created years ago. I just tested one with dvpackager and the output mkv is out of sync. Running FFmpeg 4.3.1 and dvrescue 0.20.06 after brew upgrades today. Should I try again with the dev FFmpeg mentioned above?

**Comment by dericed** [comment] 2021-02-20 16:11
Hi @cmhosale @iamdamosuzuki, I've adjusted some of the way timing is calculated in dvpackager. Could you retest with the latest builds at https://old.mediaarea.net/download/snapshots/binary/dvrescue/.

**Comment by cmhosale** [comment] 2021-03-03 20:25
tested the same file on 20.11 and the sync issue still occurs

`(standard_in) 2: parse error
ERROR: In afc2004007_066_mv002_00-00-00.000000.mkv the video track is 3444240.000000 milliseconds and the audio track is 3443206.000000. These tracks may lose sync.
FYI: Packaged to afc2004007_066_mv002_00-00-00.000000.mkv.
ERROR: afc2004007_066_mv002.dv contained 12386880000 bytes of DV, but the outputs contain  bytes of DV.`

**Comment by dericed** [comment] 2021-03-03 20:41
Thanks @cmhosale, I think this was with a recent daily build and not version 20.11, right?

**Comment by cmhosale** [comment] 2021-03-03 20:43
oh yes my mistake - v.0.20.11.20210301. Build from Monday.

**Comment by dericed** [comment] 2021-03-03 21:19
can you run `mkdir -p /Users/cmh/Desktop/afc2004007_066_mv002.dv_dvrescue` and retry. I think the step to make the output folder might have broken.

**Comment by cmhosale** [comment] 2021-03-03 21:29
I made the dir as you requested and the results are the same, with the same error output. FWIW it had successfully created a folder during the first test.

**Comment by dericed** [comment] 2021-03-03 21:41
Hi @cmhosale, thanks I found that the issue is because I was testing to make sure that the bytes of dv in the culminated outputs matched the bytes of dv from the input. To evaluate that in the output I was using mediainfo's `Video;%StreamSize_Encoded%` value which Mediainfo reports for QuickTime but does not report for Matroska, which is what you were using. I'll revise this test to adjust for comparing dv input to dv-in-mkv output.
But can you confirm that the mkv is out of sync?
cc @JeromeMartinez

**Comment by cmhosale** [comment] 2021-03-03 21:51
thanks @dericed! Yes, confirming the mkv is out of sync

**Comment by dericed** [comment] 2021-03-03 21:53
what do you get when you run `/usr/local/opt/ffmpegdecklink/bin/ffmpeg-dl`

**Comment by cmhosale** [comment] 2021-03-03 21:57
I've got no such file or directory there. If it is relevant I originally built dvrescue with brew, and then today installed the daily build with the Mac package from the downloads.

**Comment by dericed** [comment] 2021-03-03 22:42
I think the issue is that dvpackager is calling on your locally installed ffmpeg which doesn't include [this patch](https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/76fbb0052df471075858c1cb82b04c8be7adba8d). So either you'd have to reinstall a version of ffmpeg to include that or use ffmpegdecklink via `brew install amiaopensource/amiaos/ffmpegdecklink`. Let us know if that works. We should probably add a test to verify that the ffmpeg used qualifies for use if the dv does contain sparse audio.

**Comment by cmhosale** [comment] 2021-03-03 22:47
I went the ffmpegdecklink route and it worked well! MKV is in sync! In Jan when I reported the issue I'm pretty sure I had been trying with the most recent common brew formula ffmpeg, but maybe the patch wasn't in that one. Anyways, good to know, thank you!

**Comment by dericed** [comment] 2021-03-03 22:49
That patch wasn't introduced into ffmpeg until December 2020. There were a few other workarounds before but not as good as this method. I'll add a check that the ffmpeg qualifies, thanks so so much for this testing and feedback.

**Comment by dericed** [comment] 2021-03-06 13:27
Will close based @cmhosale's tests. @iamdamosuzuki, please reopen if you see anything different.

**Closed** 2021-03-06 13:47 UTC
