### ISSUE TITLE
Dropped frames

### ISSUE THREAD

**Issue by tomackroyd** [mipops/dvrescue#34] opened 2019-12-21 04:23 UTC
I am setting up a home DV archiving project and am experimenting with vrecord and dvrescue.

I recently ran five continuous DV captures using iMovie, Final Cut Pro 7, vrecord, and QuickTime Player 7’s “New Movie Recording” function. I wanted to compare results.
These were from the start of the same miniDV tape, of approximately the same duration, 9m36s. All captures were from a Sony DSR-40P (PAL), via Firewire, playing a tape recorded in 2002 on a Sony DV camera (I think the TRV900?)

I named all capture files with “P09” which is the source tape reelname.

**2010 Mac Pro, Snow Leopard**
1. iMovie, resulting in 8 .dv files
iMovie breaks dv captures up based on date/timestamp discontinuities. Files are named e.g. "clip-2002-10-26 15;05;22.dv"
Media Info gives accurate record dates and "timecode" for all clips
e.g. Media Info “Recorded date” for the first clip is 2002-10-26 15:05:22.000
2. Final Cut Pro 7.0.3, resulting in 1 DV .mov
Media Info “Recorded date” for that whole clip is 2002-10-26 15:05:22.000

**2012 iMac, Sierra 10.12.6**

3. QTPlayer 7, resulting in 1 DV .mov
Media Info “Recorded date” is same as iMovie and FCP: 2002-10-26 15:05:22.000
4. vrecord DV capture. I cmd-tabbed away from vrecord several times during this capture.
Media Info "Recorded date" is 2019-12-19 07:27:03.000 (=capture date) - 2002 record date is not in metadata.
5. ditto, but left capture in foreground with no other activity.
Media Info "Recorded date" ditto

Resultant clips were stacked in a timeline in FCP 7 to compare. Dropped frames identified by turning visibility off and on for each layer/capture.
iMovie, FCP and QTP7 clips captured the same frames with no dropped frames reported.
vrecord take 1 resulted in 3 breaks: 3 frames dropped, 2 frames dropped, 1 frame dropped
vrecord take 2 resulted in two breaks: 2 frames dropped, 5 frames dropped

All logs zipped here:
[DV_CAPTURE_2019-12_P09_LOGS.zip](https://github.com/mipops/dvrescue/files/3991048/DV_CAPTURE_2019-12_P09_LOGS.zip)
Zip contents:
DV_CAPTURE_2019-12_P09_LOGS:
 P09_FCP7_terminal_dvrescue.txt
 P09_iMovie_terminal_dvrescue.txt
 P09_QTP7_terminal_dvrescue.txt
 vrecord_take_1:
  P09_capture_options.log
  P09_ffmpeg_decklink_input.log
  P09_QC_output_graphs.jpeg
  P09_terminal_capture.txt
  P09_terminal_dvrescue.txt
 vrecord_take_2:
  P09_TAKE_2_capture_options.log
  P09_TAKE_2_ffmpeg_decklink_input.log
  P09_TAKE_2_QC_output_graphs.jpeg
  P09_TAKE_2_terminal_capture.txt
  P09_TAKE_2_terminal_dvrescue.txt

I can run other reports on these clips - just let me know. I have QCtools xmls but they're quite large.
Explicit instructions are best :-)

Tom

**Comment by kieranjol** [comment] 2019-12-21 09:55
Woah, excellent report!

**Comment by dericed** [comment] 2019-12-21 15:57
Thanks, this report is so helpful. So far I found two issues:
- vrecord used -f dv rather than -f rawvideo when handling the dv stream so rather than simply moving it along it was remuxed.
- we set `-metadata creation_time=now` which with decklink is helpful since we record when we digitize, however this data is already digital and we intend to sustain it as-is. I've added a condition to drop this.

@tomackroyd, could you test https://github.com/amiaopensource/vrecord/pull/483/files. Let me know if you need any help testing from a branch

**Comment by ablwr** [comment] 2019-12-21 22:04
Thanks for sharing this @tomackroyd !

**Comment by tomackroyd** [comment] 2019-12-21 22:36
@dericed Sorry, but I will need help testing from that branch, I don't know how to compile. Using macOS Sierra Terminal.
Tom

**Comment by tomackroyd** [comment] 2020-01-04 21:59
> @tomackroyd, could you test https://github.com/amiaopensource/vrecord/pull/483/files. Let me know if you need any help testing from a branch

Could still do with a little help running this, when you have a minute. Or does it need to approved and merged before I test? - Tom

**Comment by dericed** [comment] 2020-01-04 22:14
Hi @tomackroyd, thanks for offering, could you try this:

```
git clone --branch dv-fixes https://github.com/amiaopensource/vrecord.git vrecord-dv-fixes
cd vrecord-dv-fixes
```

Then run vrecord prefixed with a `./` such as `./vrecord -e`

**Comment by tomackroyd** [comment] 2020-01-04 23:53
Thanks, @dericed. Have run another test from that branch.

Struggling with this tape - playing from the beginning now causes complete head clogs after around 10" playback. Used a cleaning tape.

Started take 3 about 20" in. This time only one capture break - frames 5871 and 5872 were dropped. Worth noting that all the vrecord dropped frames differ from take to take.

When capturing is finished, QCTools runs and appends text to what is saved in the ffmpeg_decklink_input.log. This reports the dropped frames! I've included this in the logs below.

File "recorded date" now reflects camera record date 2002-10-26 15:05:43.000

Logs here:
[DV_CAPTURE_P09_LOGS_TAKE_3_2019-01-05.zip](https://github.com/mipops/dvrescue/files/4022710/DV_CAPTURE_P09_LOGS_TAKE_3_2019-01-05.zip)

**Comment by dericed** [comment] 2020-01-09 19:00
Hi @tomackroyd, can you try with this alternate ffmpeg and see if it has an impact on dropped frames.

```
brew uninstall --ignore-dependencies ffmpegdecklink
brew install https://gist.githubusercontent.com/dericed/56cd81f18293d1f9ef43b25d75e27c51/raw/75c0c720de6d0b99109f459269ae1834d9893824/ffmpegdecklink.rb
```

**Comment by tomackroyd** [comment] 2020-01-10 08:16
@dericed Cheers. I ran P09 take 4 through this alternate. Longer take (13m48s), dropped frames persist (all single, interestingly), see QCTools report at end of terminal output log, spoiler:

> WARNING: There were presentation timestamp discontinuities in the file's frame MD5s for these frame ranges: 4655-4655 6946-6946 10912-10912 14403-14403 19656-19656 . This error   
> may indicate frames dropped by FFmpeg or vrecord. The file may have sync issues. 

Logs here:
[DV_CAPTURE_P09_LOGS_TAKE_4_2019-01-10.zip](https://github.com/mipops/dvrescue/files/4044557/DV_CAPTURE_P09_LOGS_TAKE_4_2019-01-10.zip)
 - Tom

**Comment by tomackroyd** [comment] 2020-01-10 08:18
@dericed PS Just to show my working, here's the install log:
[dericed_alternate_ffmpeglink_install_2020-01-10.txt](https://github.com/mipops/dvrescue/files/4044571/dericed_alternate_ffmpeglink_install_2020-01-10.txt)

**Comment by dericed** [comment] 2020-01-10 15:59
Hi @tomackroyd take 4, uses the prior version of vrecord before https://github.com/mipops/dvrescue/issues/34#issuecomment-570824444. Could you now rerun with the comment there and the revised ffmpegdecklink?
btw the notice of dropped frames is derived from the framemd5 report rather than qctools.

**Comment by tomackroyd** [comment] 2020-01-10 21:04
Hi @dericed Cannot install:
`GPT1:~ GPT1$ cd /usr/local/Cellar/vrecord
GPT1:vrecord GPT1$ ls
2019-11-14
GPT1:vrecord GPT1$ git clone --branch dv-fixes https://github.com/amiaopensource/vrecord.git vrecord-dv-fixes
Cloning into 'vrecord-dv-fixes'...
fatal: Remote branch dv-fixes not found in upstream origin
`

**Comment by tomackroyd** [comment] 2020-01-10 21:32
Thanks @dericed. That version must have been deleted in the alt ffmpegdecklink install process, could not reinstall:
`GPT1:~ GPT1$ cd /usr/local/Cellar/vrecord
GPT1:vrecord GPT1$ ls
2019-11-14
GPT1:vrecord GPT1$ git clone --branch dv-fixes https://github.com/amiaopensource/vrecord.git vrecord-dv-fixes
Cloning into 'vrecord-dv-fixes'...
fatal: Remote branch dv-fixes not found in upstream origin`
so restored "vrecord-dv-fixes" directory only from backup.
Ran take 5, back to approx 9m30s recording, two dropped frames this time, logs here:
[DV_CAPTURE_P09_LOGS_TAKE_5_2019-01-11.zip](https://github.com/mipops/dvrescue/files/4048078/DV_CAPTURE_P09_LOGS_TAKE_5_2019-01-11.zip)

**Comment by dericed** [comment] 2020-01-10 21:39
ooops, this is because dv-fixes were merged. hmmm, could you try with `Unfiltered` playback, that would make the processing much simpler

**Comment by tomackroyd** [comment] 2020-01-10 21:40
Also of interest to this project, I ran AVCVideoCap successfully the other day on the same bit of tape, here's a dvrescue file:
[P09_AVCVideoCap_2020-01-07_dvrescue.txt](https://github.com/mipops/dvrescue/files/4048117/P09_AVCVideoCap_2020-01-07_dvrescue.txt)

This seems to be the only way on my configuration other than vrecord to capture a .dv stream. FCP7 dv capture crashes, QuickTime 7 captures to .mov, QuickTime X captures to AVC, iMovie version I have does not capture FireWire.

**Comment by tomackroyd** [comment] 2020-01-10 21:41
> ooops, this is because dv-fixes were merged. hmmm, could you try with `Unfiltered` playback, that would make the processing much simpler

How do I do that?

**Comment by dericed** [comment] 2020-01-10 21:42
in `./vrecord -e` change "Full Range Visual" to "Unfiltered"

**Comment by dericed** [comment] 2020-01-10 21:43
when quicktime 7 captures to mov, you can extract the dv with ffmpeg via:
`ffmpeg -i IMOVIE.mov -c:v copy -map 0:v:0 -f rawvideo extracted.dv`

**Comment by tomackroyd** [comment] 2020-01-10 22:07
> in `./vrecord -e` change "Full Range Visual" to "Unfiltered"

Done. Finger trouble means take 6 turned into take 56. Dropped frames persist, two quite large, I saw one happen - 7 frames dropped.
[DV_CAPTURE_P09_LOGS_TAKE_6_2019-01-11.zip](https://github.com/mipops/dvrescue/files/4048256/DV_CAPTURE_P09_LOGS_TAKE_6_2019-01-11.zip)

**Comment by tomackroyd** [comment] 2020-01-10 22:29
> when quicktime 7 captures to mov, you can extract the dv with ffmpeg via:
> `ffmpeg -i IMOVIE.mov -c:v copy -map 0:v:0 -f rawvideo extracted.dv`

Is there any data or metadata loss in this process?

**Comment by tomackroyd** [comment] 2020-01-10 22:33
> Hi @tomackroyd, can you try with this alternate ffmpeg and see if it has an impact on dropped frames.
> 
> ```
> brew uninstall --ignore-dependencies ffmpegdecklink
> brew install https://gist.githubusercontent.com/dericed/56cd81f18293d1f9ef43b25d75e27c51/raw/75c0c720de6d0b99109f459269ae1834d9893824/ffmpegdecklink.rb
> ```

Hi @dericed. Out of interest, what differs with this version of ffmpegdecklink?

**Comment by dericed** [comment] 2020-01-13 13:40
@tomackroyd see the bottom of the referenced patch. It changes an avfoundation flag, setAlwaysDiscardsLateVideoFrames:NO.

**Comment by dericed** [comment] 2020-01-13 13:48
@tomackroyd with the copy of vrecord that you downloaded, could you try:
`./vrecord -I '-thread_queue_size 512'`

**Comment by tomackroyd** [comment] 2020-01-14 08:30
Done. Dropped frames persist, one block right at the start: `[…] timestamp discontinuities in the file's frame MD5s for these frame ranges: 2-8 799-800 8657-8657 […]` (I saw the playback freeze at one point for what looked like 10 frames but that didn't end up in dropped frames in the resulting file.)
Logs:
[P09_take_7_thread_512_logs.zip](https://github.com/mipops/dvrescue/files/4058090/P09_take_7_thread_512_logs.zip)

**Comment by richardpl** [comment] 2020-01-14 16:52
What about capturing without playback filters active?

**Comment by tomackroyd** [comment] 2020-01-15 07:46
> What about capturing without playback filters active?

Do you mean without seeing the recording as it's being captured? How do I turn that off?
Tom

**Comment by dericed** [comment] 2020-01-15 16:30
Hi @tomackroyd, I think the simplest command in your case would be:

```
/usr/local/opt/ffmpegdecklink/bin/ffmpeg-dl -f avfoundation -capture_raw_data true -i DV -c copy -map 0 -f rawvideo test.dv -an -f framemd5 test.framemd5
```

This simply reads from the avfoundation input and writes the file and the framemd5s. After you end that recording, you could test the framemd5 for pts discontinuity (dropped frames) like this:

```
cat test.framemd5 | grep -v "^#" | cut -d, -f3 | sed 's/ //g' | grep -v "^0$" | awk '$1!=p+1{printf p+1"-"$1-1" "}{p=$1}'
```

Feasibly you could also remove the framemd5 output and just do: 
```
/usr/local/opt/ffmpegdecklink/bin/ffmpeg-dl -f avfoundation -capture_raw_data true -i DV -c copy -map 0 -f rawvideo test2.dv
```

but in that case, I think you'd need dvrescue report to identify dropped frames.

**Comment by tomackroyd** [comment] 2020-01-16 06:31
Thanks. Test completed. (I went and had dinner so this is a long capture :-) 
Multiple dropped frames:
[P09_raw_2020-01-16_dvrescue.log](https://github.com/mipops/dvrescue/files/4069654/P09_raw_2020-01-16_dvrescue.log)
[P09_raw_2020-01-16_Terminal_Saved_Output.txt](https://github.com/mipops/dvrescue/files/4069655/P09_raw_2020-01-16_Terminal_Saved_Output.txt)

**Comment by tomackroyd** [comment] 2020-01-16 06:38
One interesting note, and I feel I should be able to describe this more technically: the replay monitoring for these captures shows repeated pixels at the start of each line, and also if you look at e.g. sky you can see what looks like spatially offset colour captures from the chip. There is blanking at the end of the line too. QuickTime playback sometimes won't show this because of the whole aperture conforming options thing. But my test 50fps YouTube upload shows it quite well. (See the AvHackers Zulip "video_digitisation/Home dv project" thread for those that have access.)

**Comment by dericed** [comment] 2020-01-16 15:40
To summary the test of @tomackroyd's prior comment, the command `/usr/local/opt/ffmpegdecklink/bin/ffmpeg-dl -f avfoundation -capture_raw_data true -i DV -c copy -map 0 -f rawvideo /Users/GPT1/Movies/vrecord\ tests/P09/P09_raw_2020-01-16/test.dv -an -f framemd5 test.framemd5`
resulting in a capture with dropped frames (9 altogether):
`7603-7605 7618 19563 21064 21814 26808 29254`.

I was curious if the quality of the frame matters (as many frames show substantial error concealment warnings), but the dropped frames are all for the most part separated by frames with decoding errors by several seconds.

@richardpl, @thiloborgmann, any recommendation on if any more verbose use would give any indication of why the data is dropped. The ffmpeg output doesn't even hint at the dropped, we only know by the pts gap in the 2nd output (framemd5) and the breaks of patterns in the embedded dv metadata and dv is such a low data rate it's hard to find what issue remains.

**Comment by tomackroyd** [comment] 2020-01-17 01:53
Bear in mind other methods of capturing from the same tape, in the same deck, result in few - if any - dropped frames. (The Final Cut Pro capture is a good example.) One possible (complex) route would be to identify via timestamp all dropped frames from all the vrecord sessions, and graph the result to see what pops out.
Visually there seems nothing major going on either side of these dropped frames. It's hard to know how much error concealment is happening, but the recording and playback seem good. There are a couple of points during the recording of this particular tape where the camera was being shaken or physically knocked, and this has resulted in at least on record error that is duplicated across all captures of that scene.

**Comment by dericed** [comment] 2020-01-18 16:20
@libbyhopfauf tested ffmpegdecklink with the avfoundation patch and it was a big improvement. I included it in the recent ffmpegdecklink to be based on ffmpeg 4.2.2 with the patch, see https://github.com/amiaopensource/homebrew-amiaos/pull/217. @tomackroyd, could you run `brew upgrade` and retry your test. :-D

**Comment by libbyhopfauf** [comment] 2020-01-20 21:34
@tomackroyd In addition to the patch, I was wondering if you have cleaned your deck recently (manually, without a cleaning tape). Also, could send a link to the capture that was done on the same deck with the same tape in Final Cut Pro? I was to test something. Thank you!

**Comment by libbyhopfauf** [comment] 2020-01-20 21:38
> > What about capturing without playback filters active?
> 
> Do you mean without seeing the recording as it's being captured? How do I turn that off?
> Tom

If you go into "Edit Settings" mode, there is an options that says "Select View (for recording)." If you select "Unfiltered" from the list, this will turn off the other playback filters for recording which makes it so that less processing is going on during capture. At MIPoPS, this is the view that we have to use for all captures, otherwise we end up with tons of dropped frames, PTS discontinuities or sometimes vrecord will crash.

**Comment by tomackroyd** [comment] 2020-01-23 08:35
@libbyhopfauf I have only been using a cleaning tape - have not opened the deck up, makes me a bit nervous. Should I clean anything but the heads?
FCP7 capture here: https://www.dropbox.com/s/v531b83chzrp8on/P09_FCP7.mov?dl=0

@dericed Have run another test, unfiltered playback, following a `brew upgrade` Dropped frames persist. Logs here:
[DVCAPTURE_P09_take_9_2020-01-23_logs.zip](https://github.com/mipops/dvrescue/files/4102016/DVCAPTURE_P09_take_9_2020-01-23_logs.zip)
I have a feeling playback of this tape is worsening. I'm seeing much more dropout than previously, and regular dropped frames of >3 duration. Might be time to try a different tape.

**Comment by tomackroyd** [comment] 2020-01-25 05:43
Different tape, dropped frames persist. I ran a capture of the same tape using QTP7 - no dropped frames that I can tell - I supered one over the other in FCP.
I'm regularly seeing frames dropped right at the beginning of vrecord captures. I think this is fine - it's the beginning of the recording. The QTP7 dvrescue log will give an idea of how **that** capture needed to "settle in". Logs:
[P01_QTP7_2020-01-25_dvrescue.txt](https://github.com/mipops/dvrescue/files/4111653/P01_QTP7_2020-01-25_dvrescue.txt)
[P01_vrecord_take_1_2020-01-25.zip](https://github.com/mipops/dvrescue/files/4111654/P01_vrecord_take_1_2020-01-25.zip)

**Comment by tomackroyd** [comment] 2020-01-25 06:01
Here's a test from further down the same tape. This is an edit laid back to the tape from Lightworks to a DVCAM deck. So it's a DVCAM recording i.e. with timecode and at the higher tape speed. Was interested to see if this made a difference.
No dropped frames in the 3m22s duration.
[P01_DVCAM_recording_2020-01-25_logs.zip](https://github.com/mipops/dvrescue/files/4111663/P01_DVCAM_recording_2020-01-25_logs.zip)

**Comment by tomackroyd** [comment] 2020-02-02 00:34
Hi @libbyhopfauf - I'll need to delete that file from my Dropbox soon - can you let me know when/if you have successfully downloaded it?

**Comment by libbyhopfauf** [comment] 2020-02-14 00:38
@tomackroyd I apologize! I just now saw this! Would it be possible for you to upload it again?

I would recommend cleaning the whole tape path (the heads and any of the guides that the tape runs along) manually since sometimes cleaning tapes can end up spreading debris around instead of removing it.

**Comment by tomackroyd** [comment] 2020-02-14 23:23
@libbyhopfauf
> @tomackroyd I apologize! I just now saw this! Would it be possible for you to upload it again?
Done!

**Comment by libbyhopfauf** [comment] 2020-02-20 00:16
@tomackroyd awesome! Thank you! Downloading now! I'll run my test and let you know what I find!

**Comment by dericed** [comment] 2020-05-07 02:11
Hi @tomackroyd, hope you're well. Are you able to test the new avfctl utility for capture? The latest [daily build installer](https://mediaarea.net/download/snapshots/binary/dvrescue/) will install it and then the command `avfctl -cmd capture myrecording.dv` will write the tape to a file.

**Comment by tomackroyd** [comment] 2020-05-07 07:02
@dericed Successfully captured a file. The command puts the deck into play and I just hit stop on the deck to end capture, resulting in the "Frame dropped" line below. Are there any diagnostics you want me to try out on the resulting file? The capture doesn't recognise that the stream is 16:9 FHA by the way. 

GPT1:Desktop GPT1$ avfctl -cmd capture avfctl_test_2020-05-07.dv
2020-05-07 18:52:31.746 avfctl[64463:2908870] Error loading /Library/Audio/Plug-Ins/HAL/DVCPROHDAudio.plugin/Contents/MacOS/DVCPROHDAudio:  dlopen(/Library/Audio/Plug-Ins/HAL/DVCPROHDAudio.plugin/Contents/MacOS/DVCPROHDAudio, 262): no suitable image found.  Did find:
	/Library/Audio/Plug-Ins/HAL/DVCPROHDAudio.plugin/Contents/MacOS/DVCPROHDAudio: no matching architecture in universal wrapper
	/Library/Audio/Plug-Ins/HAL/DVCPROHDAudio.plugin/Contents/MacOS/DVCPROHDAudio: no matching architecture in universal wrapper
2020-05-07 18:52:31.746 avfctl[64463:2908870] Cannot find function pointer NewPlugIn for factory C5A4CE5B-0BB8-11D8-9D75-0003939615B6 in CFBundle/CFPlugIn 0x7fd33bc111a0 </Library/Audio/Plug-Ins/HAL/DVCPROHDAudio.plugin> (bundle, not loaded)
2020-05-07 18:52:32.043 avfctl[64463:2908870] Speed changed: 0.000000 -> 1.000000
2020-05-07 18:53:12.915 avfctl[64463:2908873] Frame dropped.
2020-05-07 18:53:14.004 avfctl[64463:2908873] Speed changed: 1.000000 -> 0.000000
2020-05-07 18:53:14.004 avfctl[64463:2908873] Mode changed: 1 -> 0
2020-05-07 18:53:14.004 avfctl[64463:2908873] Stopping capturing.
GPT1:Desktop GPT1$

[avfctl_test_2020-05-07_MediaInfo.txt](https://github.com/mipops/dvrescue/files/4591237/avfctl_test_2020-05-07_MediaInfo.txt)

**Comment by tomackroyd** [comment] 2020-07-23 07:05
@dericed I know you have been busy :-) but wondered if this issue needs more testing?

**Comment by dericed** [comment] 2020-07-31 17:30
Hi @tomackroyd, am hoping at some point when avfctl notes a dropped frame, that it can stop, rewind a little, and read until it gets back to the dropped frame, and then continue writing from there, but for now it doesn't have that ability to check and go back. Would you mind sharing the results of `dvrescue avfctl_test_2020-05-07.dv > avfctl_test_2020-05-07.dv.xml`.

**Comment by tomackroyd** [comment] 2020-08-01 01:35
Hi @dericed Here's one I made at the time:
[avfctl_test_2020-05-07_dvrescue.txt](https://github.com/mipops/dvrescue/files/5009651/avfctl_test_2020-05-07_dvrescue.txt)
but for some reason if I run that script today I only get:
`<dvrescue xmlns="https://mediaarea.net/dvrescue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://mediaarea.net/dvrescue https://mediaarea.net/dvrescue/dvrescue.xsd" version="1.0">
	<creator>
		<program>dvrescue</program>
		<version>0.19.11.20200506</version>
	</creator>
</dvrescue>
`

**Comment by dericed** [comment] 2020-08-02 19:01
yikes this tape is in rough shape.

**Comment by dericed** [comment] 2020-08-02 19:06
also what deck are you using? there's some interesting behaviors here

**Comment by dericed** [comment] 2020-08-02 19:06
oops, accidental close

**Comment by tomackroyd** [comment] 2020-08-06 07:45
> also what deck are you using? there's some interesting behaviors here

Yes my setup is slightly suboptimal. I want to be able to clean the heads myself but when I took the lid off I started to worry I would damage the heads. Deck is a Sony DSR-40P. Tapes are also possibly badly recorded, who knows? (They appear to be in good condition, no mould).
I have had better captures with that avfctl tape, so results vary.
BUT
FCP7 capture *never* drops frames. iMovie capture *never* drops frames. I'm pretty certain QT7 and QT X also never drop frames. It seems using vrecord or avfctl exposes problems with tape and machine that are buried by other software.
I would be certain also that FCP7 capture would mask errors but that's all part of the built in error correction and redundancy of the format?
Tom

**Comment by dericed** [comment] 2020-08-06 11:29
Thx @tomackroyd, yes we certainly want this to work just as well on even suboptimal computers. I'm curious if FCP7 and QT7 are also <i>never</i> dropped frames. In a dvrescue xml, you would see the presence of dropped frames because of inconsistent timecode incrementation, which is noted by the `tc_nc` attribute.

I'm still working on visualizing errors from the dvrescue xmls but here's one from what you shared earlier.
![avfctl_test_2020-05-07_dvrescue txt](https://user-images.githubusercontent.com/762604/89526969-901c1280-d7b6-11ea-8fe1-72fd339a8f66.jpg)

**Comment by tomackroyd** [comment] 2020-08-07 01:45
> Thx @tomackroyd, yes we certainly want this to work just as well on even suboptimal computers. I'm curious if FCP7 and QT7 are also never dropped frames. In a dvrescue xml, you would see the presence of dropped frames because of inconsistent timecode incrementation, which is noted by the `tc_nc` attribute.
> 
> I'm still working on visualizing errors from the dvrescue xmls but here's one from what you shared earlier.
> ![avfctl_test_2020-05-07_dvrescue txt](https://user-images.githubusercontent.com/762604/89526969-901c1280-d7b6-11ea-8fe1-72fd339a8f66.jpg)

Hi @dericed See logs are top of this issue for non-dropped frames in FCP etc but dropped frames for same tape using vrecord. I have these files still and can run further interrogations. 
Tom

**Comment by dericed** [comment] 2022-08-06 19:51
Hi Tom, we've done substantial work on this since this issue was written, could you try a `dvrescue device://0 -m OUTPUT.dv --verbosity 9 --csv` and let us know if the issue is still relevant?

**Comment by tomackroyd** [comment] 2022-08-07 00:57
Great news, Dave. My original tests were carried out during the first COVID-19 lockdown here in NZ, when I had time to set up Mac Pro/Snow Leopard and the iMac with my deck and various cable converters. These setups have been retired but I have two options to progress this:
1. Set the iMac back up and repeat the process. Honestly the various alternate ffmpeg and decklink installs confused me and my usr folder is full of things I don't know how to revert. Not even sure I have the Sierra partition now.
2. Try to capture using my new MacBook Air M2. I just got this and have installed the amiaos brew tap. I have Final Cut Pro X on it but of course none of the legacy "suboptimal" configurations or QuickTime versions detailed in this thread.

Put me to work!

**Comment by tomackroyd** [comment] 2022-08-07 01:26
But fwiw this is from the iMac High Sierra partition
iMac:~ GPT1$ dvrescue device://0 -m OUTPUT.dv --verbosity 9 --csv
<?xml version="1.0" encoding="UTF-8"?>
<dvrescue xmlns="https://mediaarea.net/dvrescue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://mediaarea.net/dvrescue https://mediaarea.net/dvrescue/dvrescue.xsd" version="1.1">
	<creator>
		<program>dvrescue</program>
		<version>0.20.06</version>
	</creator>
</dvrescue>
iMac:~ GPT1$

**Comment by dericed** [comment] 2022-09-16 18:38
will close, but please reopen if you find more dropped frames. :)

**Closed by dericed** 2022-09-16 18:38 UTC
