### ISSUE TITLE
frames with full_conceal_vid contain unneeded dseq nodes

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#208] opened 2021-01-29 12:29 UTC
example: 
[BCD00004_take1.dv.3frames.dv.zip](https://github.com/mipops/dvrescue/files/5893817/BCD00004_take1.dv.3frames.dv.zip)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<dvrescue xmlns="https://mediaarea.net/dvrescue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://mediaarea.net/dvrescue https://mediaarea.net/dvrescue/dvrescue.xsd" version="1.1">
	<creator>
		<program>dvrescue</program>
		<version>0.20.11.20210126</version>
	</creator>
	<media ref="BCD00004_take1.dv.3frames.dv" format="DV" size="360000">
		<frames count="3" pts="00:00:00.000000" end_pts="00:00:00.100100" size="720x480" video_rate="30000/1001" aspect_ratio="4/3" audio_rate="48000" channels="2">
			<frame n="0" pos="0" pts="00:00:00.000000" arb="1" full_conceal_vid="1">
				<dseq n="0">
				</dseq>
				<dseq n="1">
				</dseq>
				<dseq n="2">
				</dseq>
				<dseq n="3">
				</dseq>
				<dseq n="4">
				</dseq>
				<dseq n="5">
				</dseq>
				<dseq n="6">
				</dseq>
				<dseq n="7">
				</dseq>
				<dseq n="8">
				</dseq>
				<dseq n="9">
				</dseq>
			</frame>
			<frame n="1" pos="120000" pts="00:00:00.033367" arb="2" full_conceal_vid="1">
				<dseq n="0">
				</dseq>
				<dseq n="1">
				</dseq>
				<dseq n="2">
				</dseq>
				<dseq n="3">
				</dseq>
				<dseq n="4">
				</dseq>
				<dseq n="5">
				</dseq>
				<dseq n="6">
				</dseq>
				<dseq n="7">
				</dseq>
				<dseq n="8">
				</dseq>
				<dseq n="9">
				</dseq>
			</frame>
			<frame n="2" pos="240000" pts="00:00:00.066733" arb="3" full_conceal_vid="1">
				<dseq n="0">
				</dseq>
				<dseq n="1">
				</dseq>
				<dseq n="2">
				</dseq>
				<dseq n="3">
				</dseq>
				<dseq n="4">
				</dseq>
				<dseq n="5">
				</dseq>
				<dseq n="6">
				</dseq>
				<dseq n="7">
				</dseq>
				<dseq n="8">
				</dseq>
				<dseq n="9">
				</dseq>
			</frame>
		</frames>
	</media>
</dvrescue>
```

should be
```xml
<?xml version="1.0" encoding="UTF-8"?>
<dvrescue xmlns="https://mediaarea.net/dvrescue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://mediaarea.net/dvrescue https://mediaarea.net/dvrescue/dvrescue.xsd" version="1.1">
	<creator>
		<program>dvrescue</program>
		<version>0.20.11.20210126</version>
	</creator>
	<media ref="BCD00004_take1.dv.3frames.dv" format="DV" size="360000">
		<frames count="3" pts="00:00:00.000000" end_pts="00:00:00.100100" size="720x480" video_rate="30000/1001" aspect_ratio="4/3" audio_rate="48000" channels="2">
			<frame n="0" pos="0" pts="00:00:00.000000" arb="1" full_conceal_vid="1"/>
			<frame n="1" pos="120000" pts="00:00:00.033367" arb="2" full_conceal_vid="1"/>
			<frame n="2" pos="240000" pts="00:00:00.066733" arb="3" full_conceal_vid="1"/>
		</frames>
	</media>
</dvrescue>
```

**Comment by JeromeMartinez** [comment] 2021-01-30 00:17
Duplicate of https://github.com/mipops/dvrescue/issues/188.

**Closed by JeromeMartinez** 2021-01-30 00:17 UTC

**Comment by dericed** [comment] 2021-01-30 02:13
thx, tested & fixed.
